[general]
lunarEventChance = 0.2
[events]
bloodMoonWeight = 60
crimsonMoonWeight = 20
minerMoonWeight = 40
whiteMoonWeight = 10
tinyMoonWeight = 10
bigMoonWeight = 10
badOmenMoonWeight = 0
heroMoonWeight = 5
eclipseMoon = 2
[crimson]
crimsonReplacements = ["minecraft:zombie,minecraft:zombified_piglin", "minecraft:husk,minecraft:zombified_piglin", "minecraft:drowned,minecraft:zombified_piglin", "minecraft:skeleton,minecraft:wither_skeleton", "minecraft:creeper,minecraft:ghast", "minecraft:slime,minecraft:magma_cube", "minecraft:spider,minecraft:zoglin"]
