
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 456356
	#The name of the modpack
	modpackName = "Medieval MC [FORGE] 1.16.5"
	#The version of the modpack
	modpackVersion = "v59"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

