#
############################################
#If Enabled, armor weights will be displayed in pounds rather than kilograms
#-------------------------------------------
#Default: false
#-------------------------------------------
"Boolean: Display Weights in Pounds" = false

