
#Common configuration settings
[common]
	#Determines whether or not the backpack should be dropped on death
	keepBackpackOnDeath = false
	#The amount of slot columns in the backpack inventory.
	#Range: 1 ~ 13
	backpackInventorySizeColumns = 9
	#The amount of slot rows in the backpack inventory.
	#Range: 1 ~ 7
	backpackInventorySize = 4

	[common.wandering_trader]
		#If enabled, allows wandering traders to have a backpack equipped when they spawn.
		spawnBackpackOnWanderingTraders = true
		#The chance a Wandering Trader will spawn with a backpack. The chance is interpreted as one out of x, with x being the number given from this config option.
		#Range: 1 ~ 100
		wanderingTraderBackpackChance = 2
		#The maximum distance a Wandering Trader can detect a player. The longer the distance, the more difficult the challenge to pickpocket their backpack.
		#Range: 1.0 ~ 32.0
		wanderingTraderMaxDetectionDistance = 10.0
		#The time (in ticks) a Wandering Trader will wait before it decides to forget about a detected player. The Wandering Trader will wait indefinitely if the detected player is within the maximum detection distance.
		#Range: 1 ~ 12000
		wanderingTraderForgetTime = 200
		#If true, allows players who are disliked by Wandering Traders to continue to trade normally with them. A player is considered disliked if they are caught when trying to pickpocket a Wandering Trader's backpack.
		dislikedPlayersCanTrade = false
		#The amount of time (in ticks) a player has to wait before a Wandering Trader will like them again. If a player gets caught pickpocketing a Wandering Trader, the cooldown will be reset
		#Range: 0 ~ 24000
		dislikeCooldown = 6000
		#Instead of generating trades as loot in the Wandering Traders backpacks, only generate emeralds.
		generateEmeraldsOnly = false
		#The maximum multiplier to apply when generating loot in the Wandering Trader backpack
		#Range: 1 ~ 64
		maxLootMultiplier = 12
		#The maximum size of an emerald stack that can generate in the Wandering Trader backpack
		#Range: 1 ~ 64
		maxEmeraldStack = 32

