
[Tooltips]
	#Gives Aether Dungeon Loot a certain rarity in form of a tooltip
	"Rarity System" = true
	#Displays the Moas Mid-Air Jumps and Speed as a tooltip on the egg
	"Moa Egg Tooltips" = true
	#Displays what mob is summoned by Trapped Dungeon Blocks as well as what boss is required to unlock Boss Doorway Blocks on the item
	"Dungeon Block Tooltips" = true

[GUI]
	#Gives Ancient Aether Bosses custom boss bar designs
	"Custom Boss Bars" = true
	#Changes the Title Screen to the Ancient Aether Theme on start-up
	"Title Screen Override" = false
	#Changes the title in the Ancient Aether Title Screen to: The Aether
	"The Aether Title" = false

[Modpack]
	#Allows Ancient Aether to override Config default values, should not be disabled normally
	"Config Overrides" = true

