
[Temperature]
	#
	############################################
	#This list defines dimensional temperature modifiers
	#Dimensions in this list will multiply the tempeatures of their biomes by this value.
	#Values here should typically be between 2 (hot) and -2 (cold) but they can be anything
	#-------------------------------------------
	#Default: [minecraft:overworld,0.0, minecraft:the_nether,0.0, minecraft:the_end,0.0]
	#-------------------------------------------
	"Dimensional Temperature Modifier" = ["minecraft:overworld,0.0", "minecraft:the_nether,0.0", "minecraft:the_end,0.0"]

["Hunger & Thirst"]
	#
	############################################
	#Should the player be allowed to eat or drink beyond the maximum capacity
	#-------------------------------------------
	#Default: LIMITED
	#-------------------------------------------
	#Allowed Values: DOUBLED, LIMITED, VANILLA
	"Enum: Expanded Stomach Capacity" = "LIMITED"

[Miscellaneous]
	#
	############################################
	#Should the purified water cauldron revert back to a water cauldron when no longer underneath a campfire?
	#-------------------------------------------
	#Default: false
	#-------------------------------------------
	"Boolean: Should Purified Water Cauldron Revert" = false
	#
	############################################
	#Should Animal Fat drop from animals upon death?
	#-------------------------------------------
	#Default: true
	#-------------------------------------------
	"Boolean: Animal Fat Drops" = true
	#
	############################################
	#Can the status book be crafted from a written book and a thermometer in this world?
	#-------------------------------------------
	#Default: true
	#-------------------------------------------
	"Boolean: Status Book Crafting" = true

