
[Sleep]
	#
	############################################
	#Disabling this will prevent the mod from drawing an overlay the screen when you need sleep
	#-------------------------------------------
	#Default: true
	#-------------------------------------------
	"Boolean: Enable Tired Overlay" = true

