# Don't change this! Version used to track needed updates.
version = 0

[beam]
enable_beam = true
beam_fade_in_time = 10
beam_fade_in_distance = 15.0
beam_radius = 0.33539957
beam_height = 0.60542065
beam_y_offset = 0.5
beam_alpha = 0.75
common_shorter_beam = true
solid_beam = true
require_on_ground = true

[glow]
enable_glow = true
glow_effect_radius = 0.5

[customColorSetting]
enable_custom_color = false
color_override_by_name = {  }
color_override_by_tag = [  ]
color_override_by_modid = [  ]

[lightEffectFilter]
all_item = false
only_rare = true
only_equipment = true
whitelist_by_name = [
    "minecraft:totem_of_undying",
    "minecraft:end_crystal",
    "minecraft:nether_star",
    "minecraft:wither_skeleton_skull",
    "minecraft:diamond"
]
whitelist_by_tag = [  ]
whitelist_by_modid = [  ]
blacklist_by_name = [  ]
blacklist_by_tag = [  ]
blacklist_by_modid = [  ]