
#Combat Configuration
[combat_configuration]
	#Enable area of effects also being applied to players. 
	#If you do not want area of effects being applied to other players, disable this feature. [true / false]
	enableAreaOfEffectOnOtherPlayers = false
	#Enable limiting area of effects of mobs to only mobs they can normally target. 
	#Disabling this feature will cause mobs to hit eachother with AoE effects, but can fix unintended issues. [true / false]
	enableTargetsBasedOnGoals = true
	#Add entities that will never be targeted by aggressive Dungeons effects. 
	#To do so, enter their registry names.
	effectTargetBlacklist = []
	#Add entities that should be targetted, but aren't by aggressive Dungeons effects. 
	#To do so, enter their registry names.
	effectTargetWhitelist = []
	#Enable dual wielding. 
	#If you do not want dual wielding, disable this feature. [true / false]
	enableDualWielding = true
	#Enable two handed weapon. 
	#If you do not want two handed weapon, disable this feature. [true / false]
	enableTwoHandedWeapon = true

#Souls Configuration
[souls_configuration]
	#Enables keeping of souls upon death, disabled by default. [true / false]
	enableKeepSoulsOnDeath = false

#Artifact Configuration
[artifact_configuration]
	#Set the durability for artifacts. [0-1024, default: 64
	#Range: 0 ~ 1024
	artifactDurability = 64

#Elite Mob Configuration
[elite_mob_configuration]
	#Enables elite mobs, enabled by default. [true / false]
	enableEliteMobs = false
	#Base chance of an elite mob spawning. [0.0 - 1.0] 
	#Calculation: chance * difficulty.getSpecialMultiplier() 
	#Base chance for vanilla armor spawning is 0.15. Default is 0.15
	#Range: 0.0 ~ 1.0
	eliteMobsBaseChance = 0.15

