
["Skill Points"]
	#Range: 1 ~ 1000
	"Maximum skill points" = 100
	#Range: > 0
	"First skill point cost" = 15
	#Range: > 0
	"Last skill point cost" = 155000
	#You can set cost for each skill point instead
	"Use skill points costs array" = true
	#This list's size must be equal to maximum skill points.
	"Levelup costs" = [15, 16, 17, 19, 20, 22, 24, 26, 28, 30, 33, 36, 39, 42, 46, 50, 54, 58, 63, 68, 74, 80, 87, 94, 102, 111, 120, 130, 141, 153, 165, 179, 193, 209, 226, 245, 266, 288, 311, 337, 365, 395, 428, 463, 501, 542, 586, 634, 686, 741, 801, 866, 936, 1012, 1094, 1182, 1277, 1380, 1492, 1612, 1741, 1880, 2030, 2192, 2370, 2564, 2776, 3005, 3255, 3529, 3829, 4157, 4515, 4906, 5332, 5794, 6296, 6840, 7429, 8067, 8757, 9504, 10313, 11191, 12145, 13183, 14312, 15540, 16875, 18327, 19907, 21627, 23499, 25537, 27755, 30168, 32792, 35644, 38742, 42103, 45746, 49691, 53958, 58571, 63554, 68935, 74743, 81008, 87758, 95027, 102950, 111573, 121041, 131409, 142733, 155080]
	#Disabling this will remove chat messages when you gain a skill point.
	"Show chat messages" = true
	#Warning: If you disable this make sure you make alternative way of getting skill points.
	"Enable exprerience exchange for skill points" = true

[Gems]
	#Range: 0.0 ~ 1.0
	"Base drop chance" = 0.02

[Equipment]
	#Range: 0 ~ 4
	"Default Helmets Sockets" = 0
	#Range: 0 ~ 4
	"Default Chestplates Sockets" = 0
	#Range: 0 ~ 4
	"Default Leggings Sockets" = 0
	#Range: 0 ~ 4
	"Default Boots Sockets" = 0
	#Range: 0 ~ 4
	"Default Weapons Sockets" = 0
	#Range: 0 ~ 4
	"Default Shields Sockets" = 0
	#Range: 0 ~ 4
	"Default Rings Sockets" = 0
	#Range: 0 ~ 4
	"Default Necklaces Sockets" = 0
	#You can remove sockets from items here
	#Example: Blacklisting specific items: ["minecraft:diamond_hoe", "minecraft:golden_hoe"]
	#Example: Blacklisting whole mod: ["<mod_id>:*"]
	#Example: Blacklisting all items: ["*:*"]
	"IDs of items that shouldn't have sockets" = []
	#You can force items from other mods into equipment categories here
	"Force into helmets category" = []
	"Force into chestplates category" = []
	"Force into leggings category" = []
	"Force into boots category" = []
	"Force into shields category" = []
	"Force into melee weapons category" = []
	"Force into ranged weapons category" = []

["Amnesia Scroll"]
	#How much levels (percentage) player lose using amnesia scroll
	#Range: 0.0 ~ 1.0
	"Amnesia scroll penalty" = 0.2
	"Drop amnesia scrolls from the Ender Dragon" = true

[Experience]
	#Range: 0.0 ~ 1.0
	"Grindstone experience multiplier" = 0.25

[Mixtures]
	#Range: 0.0 ~ 2.0
	"Effects duration multiplier" = 1.0
	#Range: 0.0 ~ 2.0
	"Effects strength multiplier" = 1.0

