
[general]
	#Enable advanced configurations with tons of options to customize.
	#Note that mod configurations change with each new release, so you should keep track of changes and update extended config if you want to use new options.
	#Requires game restart to apply. Use only if you know what are you doing!
	enable_extended_config = false
	enable_relics_durability = true

