#Enables the mod to decorate underground structures and allows for more compatibility with other terrain gen mods at the expense of slower performance. Note that caves in worlds with the same seed may be populated differently depending on this setting
"Expensive Scan" = true
#The amount of non-solid blocks in front of a cave wall at which stairs and slabs spawn at a reduced rate to avoid high density narrow caves
#Range: 0 ~ 16
"Slope Threshold" = 3
#The dimensions in which cave biomes will generate in
"Dimension Whitelist" = ["minecraft:overworld"]

[Features]
	#Enable to generate stone buttons in rocky cave biomes
	"Generate Buttons" = true
	#Enable to generate vines in fungal, lush and mossy cave biomes
	"Generate Vines" = true
	#Enable to generate puddles in lush, mossy muddy, dead coral cave biomes
	"Generate Puddles" = false
	#Enable to generate stairs in cave biomes. Slope Generation Chance must also be above 0 for stairs to generate.
	"Generate Stairs" = true
	#Enable to generate slabs in cave biomes. Slope Generation Chance must also be above 0 for slabs to generate.
	"Generate Slabs" = true
	#Enable to generate patches (varying heights of slabs and snow) in cave biomes.
	"Generate Patches" = false
	#Enable to generate speleothems in cave biomes.
	"Generate Speleothems" = true
	#Enable to generate glowing foxfires in cave biomes.
	"Generate Foxfires" = true
	#Enable to generate dead bushes in mesa, sandy and sandy rocky cave biomes.
	"Generate Dead Bushes" = true
	#Enable to generate lily pads in lush, mossy and mossy rocky cave biomes.
	"Generate Lily pads" = true
	#Enable to generate wall coral in coral cave biomes.
	"Generate Wall Coral" = true
	#Enable to generate dead wall coral in dead coral cave biomes.
	"Generate Dead Wall Coral" = true
	#Enable to generate floor coral in coral cave biomes.
	"Generate Floor Coral" = true
	#Enable to generate dead floor coral in dead coral cave biomes.
	"Generate Dead Floor Coral" = true
	#Enable to generate saplings in lush and volcanic lush cave biomes.
	"Generate Saplings" = true

[Frequencies]
	#The chance of a slab or stairs generating normally in caves. Higher numbers increase the amount of slabs/stairs/slopes. Zero should stop generating them entirely.
	#Range: 0 ~ 8
	"Slope Generation Chance" = 6
	#The chance of a slab or stairs generating when within the Slope Threshold. Should be lower than the Slope Generation Chance.
	#Range: 0 ~ 7
	"Slope Threshold Generation Chance" = 2

	[Frequencies."Icy Rocky Caves"]
		#Use the "Generate Buttons" config option to stop generating them entirely.
		#Range: 1.0 ~ 100.0
		"Button Generation Chance" = 25.0

	[Frequencies."Lush Caves"]
		#Use the "Generate Lily Pads" config option to stop generating them entirely.
		#Range: 1.0 ~ 100.0
		"Lily Pad Generation Chance" = 8.33
		#Use the "Generate Saplings" config option to stop generating them entirely.
		#Range: 1.0 ~ 100.0
		"Sapling Generation Chance" = 10.0

	[Frequencies."Lush Volcanic Caves"]
		#Use the "Generate Saplings" config option to stop generating them entirely.
		#Range: 1.0 ~ 100.0
		"Sapling Generation Chance" = 10.0

	[Frequencies."Mesa Caves"]
		#Use the "Generate Dead Bushes" config option to stop generating them entirely.
		#Range: 1.0 ~ 100.0
		"Dead Bush Generation Chance" = 2.94

	[Frequencies."Mossy Caves"]
		#Use the "Generate Lily Pads" config option to stop generating them entirely.
		#Range: 1.0 ~ 100.0
		"Lily Pad Generation Chance" = 8.33

	[Frequencies."Mossy Rocky Caves"]
		#Use the "Generate Buttons" config option to stop generating them entirely.
		#Range: 1.0 ~ 100.0
		"Button Generation Chance" = 7.14
		#Use the "Generate Lily Pads" config option to stop generating them entirely.
		#Range: 1.0 ~ 100.0
		"Lily Pad Generation Chance" = 8.33

	[Frequencies."Rocky Caves"]
		#Use the "Generate Buttons" config option to stop generating them entirely.
		#Range: 1.0 ~ 100.0
		"Button Generation Chance" = 7.14

	[Frequencies."Sandy Caves"]
		#Use the "Generate Dead Bushes" config option to stop generating them entirely.
		#Range: 1.0 ~ 100.0
		"Dead Bush Generation Chance" = 3.85

	[Frequencies."Sandy Rocky Caves"]
		#Use the "Generate Buttons" config option to stop generating them entirely.
		#Range: 1.0 ~ 100.0
		"Button Generation Chance" = 7.14
		#Use the "Generate Dead Bushes" config option to stop generating them entirely.
		#Range: 1.0 ~ 100.0
		"Dead Bush Generation Chance" = 2.38

