
[Temperature]
	#
	############################################
	#This list defines dimensional temperature modifiers
	#Dimensions in this list will multiply the tempeatures of their biomes by this value.
	#Values here should typically be between 2 (hot) and -2 (cold) but they can be anything
	#-------------------------------------------
	#Default: [minecraft:overworld,0.0, minecraft:the_nether,0.0, minecraft:the_end,0.0]
	#-------------------------------------------
	"Dimensional Temperature Modifier" = ["minecraft:overworld,0.0", "minecraft:the_nether,0.0", "minecraft:the_end,0.0"]

