#
############################################
#The amount of time the player needs to sleep to recover all their energy
#-------------------------------------------
#Default: 6000
#-------------------------------------------
"Ideal Amount Of Sleep" = 6000

