#
############################################
#How much hydration is restored from the total of certain foods and drinks
#0 is 0% and 1 is 100%
#-------------------------------------------
#Default: 0.1
#-------------------------------------------
#Range: 0.0 ~ 1.0
"Float: Hydration Restoration Rate" = 0.1

