
#Defines how Sound Control logging will behave
["Logging Options"]
	#Enables/disables debug logging of the mod
	"Debug Logging" = false
	#Enables/disables display of version check information
	"Online Version Check Result" = true
	#Bitmask for toggling various debug traces
	#Range: > 0
	"Debug Flag Mask" = 0

#Options for configuring the Light Level HUD
["Light Level HUD Options"]
	#Coloring style to use for numbering
	#Allowed Values: BRIGHT, DARK
	"Color Set" = "BRIGHT"
	#The type of light level to display
	#Allowed Values: BLOCK, SKY, BLOCK_SKY
	"Display Mode" = "BLOCK"
	#Block range for light level analysis
	#Range: 8 ~ 64
	"Block Range" = 16
	#Do not show light level for blocks where mobs will not spawn
	"Hide Safe Blocks" = false
	#Light level at which mobs can spawn
	#Range: 0 ~ 15
	"Mob Spawn Light Threshold" = 7

