
[light_sources]
	entities = true
	self = true
	block_entities = true
	water_sensitive_check = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				player = true
				cat = true
				item = true
				villager = true
				bee = true
				iron_golem = true
				chest_minecart = true
				zombie = true
				skeleton = true
				creeper = true
				donkey = true
				armor_stand = true
				item_frame = true
				skeleton_horse = true
				horse = true
				pig = true
				zombie_villager = true
				squid = true
				bat = true
				allay = true
				area_effect_cloud = true
				arrow = true
				axolotl = true
				blaze = true
				boat = true
				chest_boat = true
				cave_spider = true
				chicken = true
				cod = true
				cow = true
				dolphin = true
				dragon_fireball = true
				drowned = true
				elder_guardian = true
				end_crystal = true
				ender_dragon = true
				enderman = true
				endermite = true
				evoker = true
				evoker_fangs = true
				experience_orb = true
				eye_of_ender = true
				falling_block = true
				firework_rocket = true
				fox = true
				frog = true
				ghast = true
				giant = true
				glow_item_frame = true
				glow_squid = true
				goat = true
				guardian = true
				hoglin = true
				husk = true
				illusioner = true
				fireball = true
				leash_knot = true
				lightning_bolt = true
				llama = true
				llama_spit = true
				magma_cube = true
				marker = true
				minecart = true
				command_block_minecart = true
				furnace_minecart = true
				hopper_minecart = true
				spawner_minecart = true
				tnt_minecart = true
				mule = true
				mooshroom = true
				ocelot = true
				painting = true
				panda = true
				parrot = true
				phantom = true
				piglin = true
				piglin_brute = true
				pillager = true
				polar_bear = true
				tnt = true
				pufferfish = true
				rabbit = true
				ravager = true
				salmon = true
				sheep = true
				shulker = true
				shulker_bullet = true
				silverfish = true
				slime = true
				small_fireball = true
				snow_golem = true
				snowball = true
				spectral_arrow = true
				spider = true
				stray = true
				strider = true
				tadpole = true
				egg = true
				ender_pearl = true
				experience_bottle = true
				potion = true
				trident = true
				trader_llama = true
				tropical_fish = true
				turtle = true
				vex = true
				vindicator = true
				wandering_trader = true
				warden = true
				witch = true
				wither = true
				wither_skeleton = true
				wither_skull = true
				wolf = true
				zoglin = true
				zombie_horse = true
				zombified_piglin = true
				fishing_bobber = true

			[light_sources.settings.entities.guardvillagers]
				guard = true

			[light_sources.settings.entities.ars_nouveau]
				whirlisprig = true
				starbuncle = true

			[light_sources.settings.entities.forbidden_arcanus]
				lost_soul = true

			[light_sources.settings.entities.quark]
				toretoise = true

			[light_sources.settings.entities.greekfantasy]
				naiad = true
				minotaur = true
				gorgon = true

			[light_sources.settings.entities.gnumus]
				marsupial_mousse = true
				gnumus_hunter = true
				pitcher_mouse_pac = true
				gnumus_worker = true
				gnumus_shaman = true
				gnumus_merchant = true
				big_snout = true
				small_snout = true
				projectile_vintage_rifle = true
				gnumus_hunter_not_dispawn = true
				projectile_gnumusstaff = true
				pitcher_mousse = true

			[light_sources.settings.entities.eidolon]
				zombie_brute = true
				wraith = true

			[light_sources.settings.entities.friendsandfoes]
				rascal = true

			[light_sources.settings.entities.whisperwoods]
				moth = true
				hirschgeist_fireball = true
				hidebehind = true
				wisp = true
				hirschgeist = true
				zotzpyre = true

			[light_sources.settings.entities.rottencreatures]
				undead_miner = true

			[light_sources.settings.entities.alexsmobs]
				raccoon = true
				bison = true
				terrapin = true

			[light_sources.settings.entities.stalwart_dungeons]
				projectile_spore_bottle = true
				projectile_tungsten_shield = true
				projectile_warted_tungsten_shield = true
				projectile_awful_gun = true
				projectile_awful_dungeon_spawner = true
				projectile_keeping_castle_spawner = true
				awful_ghast = true
				nether_keeper = true
				giddy_blaze = true
				incomplete_wither = true
				reinforced_blaze = true
				projectile_chorundum_shield = true
				projectile_end_dungeon_spawner = true
				propulk = true
				shelterer = true
				projectile_levitation_projectile = true
				spore_projectile = true
				nether_wart_cocoon = true
				shelterer_without_armor = true
				shulker_cannon = true
				projectile_cannon_pr = true

			[light_sources.settings.entities.strawgolem]
				strawgolem = true
				strawnggolem = true

			[light_sources.settings.entities.gateways]
				gateway = true

			[light_sources.settings.entities.jobsplus]
				fishing_bobber = true
				experience_bottle = true

			[light_sources.settings.entities.ibarnorigins]
				soul_fire_ball = true
				fixed_wither_skull = true

			[light_sources.settings.entities.iter_rpg]
				goblin = true
				goblin_warrior = true
				hobgoblin = true
				scallop = true
				giant_spider = true
				spiderling = true
				peeper = true
				mudkin = true
				mournstone = true
				weeper = true
				sorrowsealed = true
				carcass = true
				demonsoul = true
				revenant = true
				earth_elemental = true
				water_elemental = true
				air_elemental = true
				fire_elemental = true
				void_elemental = true
				bloated = true
				insatiable = true
				chain_handle = true
				caltrop_thrown = true
				blob = true
				forest_vines = true
				demonspine = true
				griever = true
				aura_soulfire = true
				aura_tearburst = true
				aura_mobspawn = true
				aura_boulder = true
				grim_boulder = true
				windswirl = true
				shimmer_projectile = true
				magic_missile = true
				debug_mobmorph = true
				elemental_charge = true
				projectile_throwing_spear = true
				projectile_gobsteel_javelin = true
				projectile_bonb = true
				projectile_the_rock = true
				projectile_driftbow = true
				projectile_marrow = true
				projectile_pearl_wand = true
				projectile_fireball_projectile = true
				projectile_droplet_projectile = true
				projectile_weeper_tear = true
				projectile_demonblood_projectile = true
				projectile_giant_weeper_tear = true
				projectile_homing_projectile = true
				void_portal = true

			[light_sources.settings.entities.corpse]
				corpse = true

			[light_sources.settings.entities.goodending]
				boat = true
				chest_boat = true
				firefly_swarm = true
				marsh = true
				woodpecker = true

			[light_sources.settings.entities.dungeons_plus]
				soul_fireball = true
				warped_axe = true

			[light_sources.settings.entities.unusualend]
				projectile_phantom_arrow = true
				endstone_trapper = true
				undead_enderling = true
				ender_blob = true
				ender_firefly = true
				endstone_golem = true
				dragling = true
				bolok = true
				warpedislandplacer = true
				projectile_creative_wandering_pearl = true

			[light_sources.settings.entities.frosted_friends]
				fridge_render = true
				snowman = true
				projectile_snowman_projectile = true

			[light_sources.settings.entities.origins]
				enderian_pearl = true

			[light_sources.settings.entities.abundant_atmosphere]
				boat = true
				chest_boat = true

			[light_sources.settings.entities.mutantmore]
				mutation_effect = true
				mutant_wither_skeleton_body_part = true
				wither_bomb = true
				mutant_shulker_trap = true
				mutant_blaze_shields = true
				thrown_mutation_potion = true
				fire_slash = true
				mutant_shulker_bullet = true
				custom_shulker_bullet = true
				mutant_blaze_fireball = true
				rodling_fireball = true
				mutant_blaze_rod_projectile = true
				test_climber = true
				concoction_w = true
				mutant_wither_skeleton = true
				mutant_blaze = true
				rodling = true
				mutant_shulker = true
				mutant_shulker_turret = true

			[light_sources.settings.entities.dungeons_libraries]
				soul_orb = true

			[light_sources.settings.entities.dungeons_gear]
				ice_cloud = true
				buzzy_nest = true
				totem_of_shielding = true
				totem_of_regeneration = true
				totem_of_soul_protection = true
				beam_entity = true
				fireworks_display = true
				soul_wizard_orb = true
				soul_wizard = true

			[light_sources.settings.entities.snowrealmagic]
				snow = true

			[light_sources.settings.entities.humancompanions]
				knight = true
				archer = true
				arbalist = true
				axeguard = true

			[light_sources.settings.entities.mutantmonsters]
				creeper_minion = true
				mutant_creeper = true
				mutant_enderman = true
				mutant_skeleton = true
				mutant_snow_golem = true
				mutant_zombie = true
				spider_pig = true
				body_part = true
				creeper_minion_egg = true
				endersoul_clone = true
				endersoul_fragment = true
				throwable_block = true
				mutant_arrow = true
				skull_spirit = true

			[light_sources.settings.entities.graveyard]
				skeleton_creeper = true
				acolyte = true
				reaper = true
				ghoul = true
				nightmare = true
				revenant = true
				falling_corpse = true
				lich = true
				wraith = true
				corrupted_pillager = true
				corrupted_vindicator = true
				ghouling = true
				skull = true
				nameless_hanged = true

			[light_sources.settings.entities.goblintraders]
				goblin_trader = true
				vein_goblin_trader = true

			[light_sources.settings.entities.epicsamurai]
				akaname = true
				kitsune = true
				enenra = true
				oni = true
				onibi = true
				shuriken = true
				kunai = true
				kitsune_projectile = true

			[light_sources.settings.entities.immersive_weathering]
				falling_icicle = true
				falling_layer = true
				falling_propagule = true

			[light_sources.settings.entities.sons_of_sins]
				gulber = true
				devourer = true
				wistiver = true
				walking_bed = true
				blud = true
				prowler = true
				kelvin = true
				butcher = true
				curse = true
				projectile_blood_pr = true

			[light_sources.settings.entities.ecologics]
				coconut_crab = true
				camel = true
				boat = true
				chest_boat = true
				penguin = true
				squirrel = true

			[light_sources.settings.entities.byg]
				boat = true
				chest_boat = true
				man_o_war = true
				pumpkin_warden = true

			[light_sources.settings.entities.phantasm]
				crystie = true

			[light_sources.settings.entities.tetra]
				thrown_modular_item = true
				extractor_projectile = true

			[light_sources.settings.entities.hexerei]
				broom = true
				boat = true
				chest_boat = true
				crow = true
				owl = true

			[light_sources.settings.entities.blue_skies]
				azulfo = true
				stardust_ram = true
				reindeer = true
				frost_spirit = true
				grittle_flatfish = true
				municipal_monkfish = true
				armored_frost_spirit = true
				crynocerous = true
				jelly_drifter = true
				snow_owl = true
				polargeist = true
				stonelet = true
				whistleshell_crab = true
				shrumpty = true
				diophyde_prowler = true
				seclam = true
				firefly = true
				cosmic_fox = true
				crystal_camel = true
				shade_monitor = true
				sliv = true
				crogre = true
				charscale_moki = true
				horizofin_tunid = true
				nyctofly = true
				venom_spider = true
				venom_spit = true
				emberback = true
				infested_swarmer = true
				gatekeeper = true
				summoner = true
				artificial_golem = true
				strange_lightning = true
				fluctuant_sphere = true
				alchemist = true
				decaying_spike = true
				starlit_crusher = true
				ent_root = true
				ent_wall = true
				ent_leaf = true
				spewter = true
				seed_bomb = true
				arachnarch = true
				venom_bomb = true
				nested_spider = true
				spear = true

