# Don't change this! Version used to track needed updates.
version = 0

[sound]
enable_sound = true
sound_volume = 0.7535539

[soundFilter]
blacklist_by_name = [  ]
blacklist_by_tag = [  ]
blacklist_by_modid = [  ]