#
############################################
#Disabling this will disable this mods well being system
#-------------------------------------------
#Default: true
#-------------------------------------------
"Boolean: Enable Well Being" = true

