[biomes]
enabled = true
textFadeInTime = 10
textDisplayTime = 50
textFadeOutTime = 10
textCooldownTime = 80
textColor = "ffffff"
textSize = 1.6
renderShadow = true
textYOffset = -37
textXOffset = 0
biomeBlacklist = "[minecraft:the_end, minecraft:river, minecraft:frozen_river]"
recentBiomeCacheSize = 10
centerText = true
resetBiomeCacheOnDimensionChange = false
onlyUpdateAtSurface = true
[dimensions]
enabled = true
textFadeInTime = 0
textDisplayTime = 70
textFadeOutTime = 20
textColor = "ffffff"
textSize = 2.9
renderShadow = true
textYOffset = 20
textXOffset = 0
dimensionBlacklist = "[]"
centerText = true
onlyUpdateAtSurface = false
[sound]
biomeVolume = 1.0
biomePitch = 1.0
dimensionVolume = 1.0
dimensionPitch = 1.0
