
[logbegone]
	phrases = ["Disconnecting VANILLA connection attempt", "Channels ", "OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. <texture> is not a valid texture name.'"]
	regex = ["Disconnecting VANILLA connection attempt", "Channels ", "OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. <texture> is not a valid texture name.'"]

