#
############################################
#Disabling this will disable this mods thirst system
#-------------------------------------------
#Default: true
#-------------------------------------------
"Boolean: Enable Thirst" = true
#
############################################
#Enabling this allows players to drink water from flowing water sources. This is only allowed for infinite water sources
#-------------------------------------------
#Default: false
#-------------------------------------------
"Boolean: Drink From Flowing Water" = false
#
############################################
#Enabling this will remove the water source block when it is drunk
#-------------------------------------------
#Default: false
#-------------------------------------------
"Boolean: Remove Source Water Block" = false
#
############################################
#The amount of thirst exaustion added to the player regardless of what the player is doing
#-------------------------------------------
#Default: 0.1125
#-------------------------------------------
#Range: 0.0 ~ 4.0
"Float: Idle Thirst Exhaustion" = 0.1125
#
############################################
#The amount of time in ticks before thirst exaustion is added to the player regardless of what the player is doing. Set to -1 to disable
#-------------------------------------------
#Default: 100
#-------------------------------------------
#Range: -1 ~ 1000
"Integer: Idle Thrist Tick Rate" = 100
#
############################################
#The amount of times we can drink water from a canteen before it's empty
#-------------------------------------------
#Default: 3
#-------------------------------------------
#Range: 1 ~ 10
"Integer: Canteen Fill Amount" = 3

